"""Bootstrap a Dify tenant for a SudoWork enterprise.

Called exactly once per enterprise by sudowork-server. Idempotency is the
caller's responsibility (it stores the returned tenant_id in its binding
table). We do not look up existing tenants by enterprise code; if invoked
twice we will produce two tenants and let the caller reconcile.

Returns the trio sudowork-server needs:
- dify_tenant_id (UUID, stored in dify_tenant_binding)
- system_account_id (UUID, used as `created_by` placeholder)
- service_api_key (the long-lived dataset/app API token, encrypted at rest
  on sudowork-server side via AES-GCM)
"""

from __future__ import annotations

import json
import logging
import os
import secrets
from dataclasses import dataclass
from typing import Optional

from configs import dify_config
from extensions.ext_database import db
from libs.helper import generate_string
from models.account import AccountStatus, TenantAccountRole
from models.model import ApiToken, ApiTokenType, DifySetup
from services.account_service import AccountService, TenantService

logger = logging.getLogger(__name__)


# 2026-06-23: P3.5 default plugin pre-installation.
# The lockfile is generated by docker/sudowork-patches/seed-plugins.sh on the
# deployment host; it maps each `<org>/<id>:<version>` spec from
# default-plugins.json to its full `<org>/<id>:<version>@<sha>` unique
# identifier. We bind-mount the patches dir into the api container at
# /app/api/sudowork_patches, so resolution is offline at provisioning time.
_DEFAULT_PLUGINS_LOCK_PATH = os.environ.get(
    "SUDOWORK_DEFAULT_PLUGINS_LOCK",
    "/app/api/sudowork_patches/default-plugins.lock.json",
)

# Where the .difypkg bytes live, viewed from inside the api container.
# Compose bind-mounts ./volumes/plugin_daemon/plugin_packages here read-only
# so we can hand the raw bytes to plugin_daemon's upload endpoint without
# any inter-container HTTP juggling.
_DEFAULT_PLUGINS_PKG_DIR = os.environ.get(
    "SUDOWORK_DEFAULT_PLUGINS_PKG_DIR",
    "/app/api/sudowork_patches/plugin_packages/langgenius",
)


def _load_default_plugin_identifiers() -> list[str]:
    """Resolve the lockfile to a list of marketplace unique_identifiers.

    Missing or empty lockfile → empty list (provisioning still succeeds, but
    the new tenant won't have any pre-installed plugins; admin can install
    them by hand). Mal-formed JSON also degrades to empty + warning instead
    of blowing up the whole provision call.
    """

    if not os.path.isfile(_DEFAULT_PLUGINS_LOCK_PATH):
        logger.info(
            "sudowork_default_plugins_lockfile_missing path=%s — no plugins will be pre-installed",
            _DEFAULT_PLUGINS_LOCK_PATH,
        )
        return []
    try:
        with open(_DEFAULT_PLUGINS_LOCK_PATH, encoding="utf-8") as f:
            doc = json.load(f)
        resolved = doc.get("resolved") or {}
        return [uid for uid in resolved.values() if uid]
    except Exception:
        logger.exception(
            "sudowork_default_plugins_lockfile_unreadable path=%s",
            _DEFAULT_PLUGINS_LOCK_PATH,
        )
        return []


def _install_default_plugins(tenant_id: str) -> None:
    """Best-effort: install the resolved default suite into the freshly
    created tenant. Failures here MUST NOT abort the tenant provisioning —
    a tenant without plugins is fixable later (admin can use the install
    button) but a half-provisioned tenant is much harder to clean up.
    """

    identifiers = _load_default_plugin_identifiers()
    if not identifiers:
        return

    try:
        # Imported lazily to keep the provisioning module light at import
        # time and so a stale plugin_service can't poison fresh deploys.
        # Note: in current Dify the PluginService class lives under
        # `core.plugin.plugin_service` — the legacy `services.plugin.*`
        # path was renamed and no longer exists.
        from core.plugin.plugin_service import PluginService
    except Exception as e:
        import traceback as _tb
        logger.exception(
            "sudowork_default_plugins_import_failed err_type=%s err=%s\nfull_tb:\n%s",
            type(e).__name__,
            e,
            _tb.format_exc(),
        )
        return

    # Only upload — DO NOT install per-tenant. Reasons:
    #
    #   - Every installed plugin spawns a long-running Python subprocess
    #     inside plugin_daemon (each plugin runs in its own venv as its
    #     own server). 44 always-on processes ≈ several GB RSS for a
    #     freshly-provisioned tenant who may never use most of them.
    #   - upload_pkg alone pushes the .difypkg to plugin_daemon, decodes
    #     the manifest, and registers a row in `plugin_declarations`.
    #     That's enough for the Studio "Install from Marketplace" button
    #     to short-circuit to install_from_local_pkg (see
    #     install_redirect.py) when admin actually clicks install for
    #     a specific provider.
    #
    # So the user trade is: tenant boots with 0 plugin processes (cheap),
    # and the FIRST click on "Install" for any given provider becomes the
    # moment its process spawns. Subsequent clicks fan out memory only
    # for providers actually in use.
    #
    # Per-plugin try/except keeps a single bad manifest (e.g. `feature:
    # polling` enum that 1.14.2 doesn't recognise) from aborting the rest.
    succeeded = 0
    failed: list[str] = []
    for uid in identifiers:
        try:
            # uid shape: "langgenius/openai:0.4.2@<sha256>"
            # filename on disk drops the "langgenius/" prefix.
            _, fname = uid.split("/", 1)
            pkg_path = os.path.join(_DEFAULT_PLUGINS_PKG_DIR, fname)
            with open(pkg_path, "rb") as fh:
                pkg_bytes = fh.read()
            PluginService.upload_pkg(tenant_id, pkg_bytes)
            succeeded += 1
        except Exception as e:
            failed.append(uid.split("@", 1)[0])
            logger.warning(
                "sudowork_default_plugin_declare_skip tenant=%s plugin=%s err=%s",
                tenant_id,
                uid,
                e,
            )
    logger.info(
        "sudowork_default_plugins_declared tenant=%s succeeded=%d failed=%d "
        "(declarations only; actual install spawns lazily per Studio click)",
        tenant_id,
        succeeded,
        len(failed),
    )
    if failed:
        logger.warning(
            "sudowork_default_plugins_partial tenant=%s skipped=%s",
            tenant_id,
            failed,
        )


# Backwards-compat alias kept in case the optional helper is ever needed
# from outside this module (we don't expose it via __all__).
_default_plugins_lock_path: Optional[str] = _DEFAULT_PLUGINS_LOCK_PATH


@dataclass(frozen=True)
class ProvisionResult:
    dify_tenant_id: str
    system_account_id: str
    service_api_key: str


_SYSTEM_EMAIL_LOCAL_PREFIX = "sudowork-system"


def _system_email(enterprise_code: str) -> str:
    domain = dify_config.SUDOWORK_ACCOUNT_EMAIL_DOMAIN or "local.sudowork"
    sanitized = "".join(ch for ch in enterprise_code if ch.isalnum() or ch in ("-", "_")) or "tenant"
    return f"{_SYSTEM_EMAIL_LOCAL_PREFIX}-{sanitized}@{domain}"


def _issue_service_api_key(tenant_id: str) -> str:
    token_str = ApiToken.generate_api_key("dataset-", 24)
    token = ApiToken()
    token.token = token_str
    token.tenant_id = tenant_id
    token.type = ApiTokenType.DATASET
    db.session.add(token)
    db.session.flush()
    return token_str


def provision(*, enterprise_code: str, enterprise_name: str) -> ProvisionResult:
    """Create Tenant + system Account + Service API key in one transaction.

    The system account uses an unguessable random password so it cannot be
    logged into via the normal email/password flow. It exists purely so Dify
    has an Account.id to attribute system-owned datasets / apps to.
    """

    enterprise_code = (enterprise_code or "").strip()
    if not enterprise_code:
        raise ValueError("enterprise_code is required")
    enterprise_name = (enterprise_name or enterprise_code).strip()

    tenant = TenantService.create_tenant(name=enterprise_name, is_setup=True)
    tenant.custom_config = json.dumps(
        {
            "sudowork_enterprise_code": enterprise_code,
            "managed_by": "sudowork",
        }
    )

    system_email = _system_email(enterprise_code)
    random_password = secrets.token_urlsafe(32)
    system_account = AccountService.create_account(
        email=system_email,
        name=f"SudoWork System ({enterprise_code})",
        interface_language="en-US",
        password=random_password,
        is_setup=True,
    )
    system_account.status = AccountStatus.ACTIVE
    TenantService.create_tenant_member(tenant, system_account, role=TenantAccountRole.OWNER.value)

    service_api_key = _issue_service_api_key(tenant.id)

    # Mark Dify's first-run setup as complete. Without this row the Studio
    # frontend's hard-coded boot check (`GET /console/api/setup`) returns
    # `step="not_started"` and force-redirects to /install — even on an SSO
    # exchange URL, even when several Tenants already exist. Upstream Dify
    # writes this row inside its own `/console/api/setup` POST handler, but
    # SudoWork bypasses that flow entirely (system-to-system provisioning
    # via /sudowork/system/tenants), so the row would otherwise never
    # appear and admins land on a broken setup form whose POST returns 403
    # ("AlreadySetupError" from tenant_count > 0). We upsert it as part of
    # the first provision; subsequent provisions are no-ops.
    if not db.session.query(DifySetup).first():
        db.session.add(DifySetup(version=dify_config.project.version))
        db.session.flush()

    db.session.commit()
    logger.info(
        "sudowork_tenant_provisioned",
        extra={
            "dify_tenant_id": tenant.id,
            "enterprise_code": enterprise_code,
            "system_account_id": system_account.id,
        },
    )

    # P3.5: auto-install the default model-provider suite so the new
    # tenant's admin can configure models immediately, without first
    # hunting through the "marketplace → install" flow. Best-effort: any
    # failure here is logged and swallowed.
    _install_default_plugins(tenant.id)

    return ProvisionResult(
        dify_tenant_id=tenant.id,
        system_account_id=system_account.id,
        service_api_key=service_api_key,
    )


# Silence unused-imports flagged by static checkers
_ = generate_string

__all__ = ["ProvisionResult", "provision"]
