"""Bootstrap a Dify tenant for a SudoWork enterprise.

Called exactly once per enterprise by sudowork-server. Idempotency is the
caller's responsibility (it stores the returned tenant_id in its binding
table). We do not look up existing tenants by enterprise code; if invoked
twice we will produce two tenants and let the caller reconcile.

Returns the trio sudowork-server needs:
- dify_tenant_id (UUID, stored in dify_tenant_binding)
- system_account_id (UUID, used as `created_by` placeholder)
- service_api_key (the long-lived dataset/app API token, encrypted at rest
  on sudowork-server side via AES-GCM)
"""

from __future__ import annotations

import json
import logging
import os
import secrets
from dataclasses import dataclass
from typing import Optional

from configs import dify_config
from extensions.ext_database import db
from libs.helper import generate_string
from models.account import AccountStatus, TenantAccountRole
from models.model import ApiToken, ApiTokenType
from services.account_service import AccountService, TenantService

logger = logging.getLogger(__name__)


# 2026-06-23: P3.5 default plugin pre-installation.
# The lockfile is generated by docker/sudowork-patches/seed-plugins.sh on the
# deployment host; it maps each `<org>/<id>:<version>` spec from
# default-plugins.json to its full `<org>/<id>:<version>@<sha>` unique
# identifier. We bind-mount the patches dir into the api container at
# /app/api/sudowork_patches, so resolution is offline at provisioning time.
_DEFAULT_PLUGINS_LOCK_PATH = os.environ.get(
    "SUDOWORK_DEFAULT_PLUGINS_LOCK",
    "/app/api/sudowork_patches/default-plugins.lock.json",
)


def _load_default_plugin_identifiers() -> list[str]:
    """Resolve the lockfile to a list of marketplace unique_identifiers.

    Missing or empty lockfile → empty list (provisioning still succeeds, but
    the new tenant won't have any pre-installed plugins; admin can install
    them by hand). Mal-formed JSON also degrades to empty + warning instead
    of blowing up the whole provision call.
    """

    if not os.path.isfile(_DEFAULT_PLUGINS_LOCK_PATH):
        logger.info(
            "sudowork_default_plugins_lockfile_missing path=%s — no plugins will be pre-installed",
            _DEFAULT_PLUGINS_LOCK_PATH,
        )
        return []
    try:
        with open(_DEFAULT_PLUGINS_LOCK_PATH, encoding="utf-8") as f:
            doc = json.load(f)
        resolved = doc.get("resolved") or {}
        return [uid for uid in resolved.values() if uid]
    except Exception:
        logger.exception(
            "sudowork_default_plugins_lockfile_unreadable path=%s",
            _DEFAULT_PLUGINS_LOCK_PATH,
        )
        return []


def _install_default_plugins(tenant_id: str) -> None:
    """Best-effort: install the resolved default suite into the freshly
    created tenant. Failures here MUST NOT abort the tenant provisioning —
    a tenant without plugins is fixable later (admin can use the install
    button) but a half-provisioned tenant is much harder to clean up.
    """

    identifiers = _load_default_plugin_identifiers()
    if not identifiers:
        return

    try:
        # Imported lazily to keep the provisioning module light at import
        # time and so a stale plugin_service can't poison fresh deploys.
        from services.plugin.plugin_service import PluginService
    except Exception as e:
        import traceback as _tb
        logger.exception(
            "sudowork_default_plugins_import_failed err_type=%s err=%s\nfull_tb:\n%s",
            type(e).__name__,
            e,
            _tb.format_exc(),
        )
        return

    # Install one-by-one rather than batching: an incompatible plugin
    # (manifest enum mismatch, etc.) would otherwise abort the entire
    # suite. Single-plugin failures are logged and skipped so the
    # remaining 40+ plugins still land in the new tenant.
    succeeded = 0
    failed: list[str] = []
    for uid in identifiers:
        try:
            PluginService.install_from_marketplace_pkg(tenant_id, [uid])
            succeeded += 1
        except Exception as e:
            failed.append(uid.split("@", 1)[0])
            logger.warning(
                "sudowork_default_plugin_skip tenant=%s plugin=%s err=%s",
                tenant_id,
                uid,
                e,
            )
    logger.info(
        "sudowork_default_plugins_installed tenant=%s succeeded=%d failed=%d",
        tenant_id,
        succeeded,
        len(failed),
    )
    if failed:
        logger.warning(
            "sudowork_default_plugins_partial tenant=%s skipped=%s",
            tenant_id,
            failed,
        )


# Backwards-compat alias kept in case the optional helper is ever needed
# from outside this module (we don't expose it via __all__).
_default_plugins_lock_path: Optional[str] = _DEFAULT_PLUGINS_LOCK_PATH


@dataclass(frozen=True)
class ProvisionResult:
    dify_tenant_id: str
    system_account_id: str
    service_api_key: str


_SYSTEM_EMAIL_LOCAL_PREFIX = "sudowork-system"


def _system_email(enterprise_code: str) -> str:
    domain = dify_config.SUDOWORK_ACCOUNT_EMAIL_DOMAIN or "local.sudowork"
    sanitized = "".join(ch for ch in enterprise_code if ch.isalnum() or ch in ("-", "_")) or "tenant"
    return f"{_SYSTEM_EMAIL_LOCAL_PREFIX}-{sanitized}@{domain}"


def _issue_service_api_key(tenant_id: str) -> str:
    token_str = ApiToken.generate_api_key("dataset-", 24)
    token = ApiToken()
    token.token = token_str
    token.tenant_id = tenant_id
    token.type = ApiTokenType.DATASET
    db.session.add(token)
    db.session.flush()
    return token_str


def provision(*, enterprise_code: str, enterprise_name: str) -> ProvisionResult:
    """Create Tenant + system Account + Service API key in one transaction.

    The system account uses an unguessable random password so it cannot be
    logged into via the normal email/password flow. It exists purely so Dify
    has an Account.id to attribute system-owned datasets / apps to.
    """

    enterprise_code = (enterprise_code or "").strip()
    if not enterprise_code:
        raise ValueError("enterprise_code is required")
    enterprise_name = (enterprise_name or enterprise_code).strip()

    tenant = TenantService.create_tenant(name=enterprise_name, is_setup=True)
    tenant.custom_config = json.dumps(
        {
            "sudowork_enterprise_code": enterprise_code,
            "managed_by": "sudowork",
        }
    )

    system_email = _system_email(enterprise_code)
    random_password = secrets.token_urlsafe(32)
    system_account = AccountService.create_account(
        email=system_email,
        name=f"SudoWork System ({enterprise_code})",
        interface_language="en-US",
        password=random_password,
        is_setup=True,
    )
    system_account.status = AccountStatus.ACTIVE
    TenantService.create_tenant_member(tenant, system_account, role=TenantAccountRole.OWNER.value)

    service_api_key = _issue_service_api_key(tenant.id)

    db.session.commit()
    logger.info(
        "sudowork_tenant_provisioned",
        extra={
            "dify_tenant_id": tenant.id,
            "enterprise_code": enterprise_code,
            "system_account_id": system_account.id,
        },
    )

    # P3.5: auto-install the default model-provider suite so the new
    # tenant's admin can configure models immediately, without first
    # hunting through the "marketplace → install" flow. Best-effort: any
    # failure here is logged and swallowed.
    _install_default_plugins(tenant.id)

    return ProvisionResult(
        dify_tenant_id=tenant.id,
        system_account_id=system_account.id,
        service_api_key=service_api_key,
    )


# Silence unused-imports flagged by static checkers
_ = generate_string

__all__ = ["ProvisionResult", "provision"]
