#!/usr/bin/env python3
"""Generate nginx sub_filter rules from Dify i18n JSON files.

Scans every web/i18n/<locale>/*.json file, finds every string value that
contains "Dify" (as a whole word, in user-facing copy), and emits an
nginx `sub_filter '<original>' '<rewritten>';` rule that swaps the brand
out at HTTP response time. Output goes into a conf snippet that's
included from nginx default.conf.template.

We DO NOT touch:
  - i18n keys (only values)
  - Strings where "Dify" is part of a URL / module name / identifier
    (we conservatively skip strings that look like URLs or contain "/")
  - Strings already rewritten on a prior run (idempotent)

Run on the host whenever Dify's i18n changes (e.g. after a Dify upgrade):
    python3 generate-rebrand-subfilters.py
    docker compose restart nginx
"""

from __future__ import annotations

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
I18N_ROOT = REPO_ROOT / "web" / "i18n"
# Output lives directly under nginx/conf.d/ so docker-compose's existing
# directory bind-mount (`./nginx/conf.d:/etc/nginx/conf.d`) picks it up
# in one step. The nginx default.conf uses `include rebrand-subfilters.conf;`
# to pull these rules in.
OUT_PATH = Path(__file__).resolve().parents[1] / "nginx" / "conf.d" / "rebrand-subfilters.conf"

BRAND_FROM = "Dify"
BRAND_TO = "Sudowork"

# nginx hard-limits sub_filter directives to 255 per location, so we
# cherry-pick:
#   - only the two locales we ship UI for (zh-Hans + en-US)
#   - only short strings (<= MAX_LEN chars) — long license/billing prose
#     is rarely seen by ordinary admins, and burning a slot per locale on
#     each would blow the budget. Such strings can be re-added by hand to
#     the conf if a customer specifically needs them removed.
LOCALES = {"zh-Hans", "en-US"}
MAX_LEN = 80
MAX_RULES = 240  # leave headroom under nginx's 255 cap


def is_user_facing(value: str) -> bool:
    """Heuristic: strings that look like prose, not URLs/identifiers."""
    if "://" in value:
        return False
    if value.startswith("/") or value.startswith("@"):
        return False
    if re.fullmatch(r"[\w\-./]+", value):
        # bare token like "Dify-1.0.0" or "dify_node" — skip
        return False
    return True


def walk(node, out: set[str]) -> None:
    if isinstance(node, dict):
        for v in node.values():
            walk(v, out)
    elif isinstance(node, list):
        for v in node:
            walk(v, out)
    elif (
        isinstance(node, str)
        and BRAND_FROM in node
        and len(node) <= MAX_LEN
        and is_user_facing(node)
    ):
        out.add(node)


def escape_nginx(s: str) -> str:
    """Escape single quotes for nginx 'literal' syntax."""
    return s.replace("\\", "\\\\").replace("'", "\\'")


def main() -> None:
    found: set[str] = set()
    if not I18N_ROOT.is_dir():
        raise SystemExit(f"i18n root not found: {I18N_ROOT}")
    for locale in LOCALES:
        loc_dir = I18N_ROOT / locale
        if not loc_dir.is_dir():
            continue
        for f in sorted(loc_dir.glob("*.json")):
            try:
                doc = json.loads(f.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                continue
            walk(doc, found)

    # Sort by length descending so the most specific (longest) phrases
    # are matched first — prevents shorter substrings from chewing up a
    # longer phrase before its dedicated rule has a chance to run.
    candidates = sorted(found, key=lambda s: (-len(s), s))
    rules = []
    for original in candidates:
        if len(rules) >= MAX_RULES:
            break
        rewritten = original.replace(BRAND_FROM, BRAND_TO)
        if rewritten == original:
            continue
        rules.append(
            f"      sub_filter '{escape_nginx(original)}' '{escape_nginx(rewritten)}';"
        )

    header = (
        "# Generated by sudowork-patches/generate-rebrand-subfilters.py — DO NOT EDIT BY HAND.\n"
        f"# {len(rules)} rule(s), source: web/i18n/{{{'|'.join(sorted(LOCALES))}}}/*.json\n"
        f"# Limits: <={MAX_LEN} chars per string, max {MAX_RULES} rules (nginx caps at 255).\n"
        "# Re-generate after Dify upgrade or i18n changes.\n"
    )
    OUT_PATH.write_text(header + "\n".join(rules) + "\n", encoding="utf-8")
    print(f"wrote {len(rules)} sub_filter rules → {OUT_PATH}")


if __name__ == "__main__":
    main()
