#!/usr/bin/env bash
#
# Seed the Dify plugin_daemon volume with .difypkg files for every plugin
# listed in `default-plugins.json`. Run this once on the deployment host
# (it needs marketplace.dify.ai access); afterwards every tenant
# auto-provisioned via sudowork-server can install these plugins WITHOUT
# any further internet egress.
#
# Idempotent: if a .difypkg already lives in plugin_packages/ we skip the
# download. Safe to rerun whenever default-plugins.json is updated.
#
# Usage:
#   ./seed-plugins.sh                                # default paths
#   PLUGIN_DIR=/custom/path ./seed-plugins.sh        # override storage
#   MARKETPLACE=https://my-mirror ./seed-plugins.sh  # use a mirror
#
# After running, restart plugin_daemon so it indexes the new packages:
#   docker compose restart plugin_daemon

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIST_FILE="${LIST_FILE:-$SCRIPT_DIR/default-plugins.json}"
PLUGIN_DIR="${PLUGIN_DIR:-$SCRIPT_DIR/../volumes/plugin_daemon/plugin_packages/langgenius}"
MARKETPLACE="${MARKETPLACE:-https://marketplace.dify.ai}"

mkdir -p "$PLUGIN_DIR"

if [[ ! -f "$LIST_FILE" ]]; then
    echo "ERROR: plugin list not found: $LIST_FILE" >&2
    exit 1
fi

# Pull plugin specs from the JSON. We rely on python3 (always present in
# our deploy hosts) instead of jq to avoid an extra dependency.
mapfile -t SPECS < <(python3 -c "
import json, sys
with open('$LIST_FILE') as f:
    d = json.load(f)
for s in d.get('plugins', []):
    print(s)
")

total=${#SPECS[@]}
echo "→ seeding $total plugin(s) into $PLUGIN_DIR"
echo

ok=0
skip=0
fail=0
# Lockfile records the resolved <unique_identifier> for each spec so the
# tenant provisioning step doesn't have to hit marketplace again. Stored
# next to default-plugins.json, picked up by Python at provision time.
LOCK_FILE="$SCRIPT_DIR/default-plugins.lock.json"
declare -a LOCK_ENTRIES=()

for spec in "${SPECS[@]}"; do
    # spec format: langgenius/openai:0.4.2  → org=langgenius, id=openai, ver=0.4.2
    org="${spec%%/*}"
    rest="${spec#*/}"
    id="${rest%%:*}"
    ver="${rest#*:}"

    # Resolve the version doc to grab the full unique_identifier (with sha).
    resolved=$(python3 -c "
import json, sys, urllib.request, urllib.error
req = urllib.request.Request(
    '$MARKETPLACE/api/v1/plugins/$org/$id/$ver',
    headers={'User-Agent': 'curl/8.0'})
try:
    with urllib.request.urlopen(req, timeout=15) as r:
        d = json.loads(r.read().decode('utf-8'), strict=False)
    if d.get('code') != 0:
        sys.exit(2)
    print(d['data']['version']['unique_identifier'])
except Exception as e:
    sys.stderr.write(str(e) + '\n')
    sys.exit(3)
")

    if [[ -z "$resolved" ]]; then
        printf "  ✗ %-45s  resolve failed\n" "$spec"
        fail=$((fail + 1))
        continue
    fi

    # File name is the suffix after "<org>/" in the unique_identifier.
    # e.g. langgenius/openai:0.4.2@xxx  →  openai:0.4.2@xxx
    fname="${resolved#*/}"
    target="$PLUGIN_DIR/$fname"

    # Track the resolved identifier for the lockfile regardless of cache.
    LOCK_ENTRIES+=("$spec=$resolved")

    if [[ -f "$target" ]]; then
        printf "  ✓ %-45s  cached\n" "$spec"
        skip=$((skip + 1))
        continue
    fi

    # URL-encode the unique_identifier for the download endpoint.
    encoded=$(python3 -c "
import urllib.parse
print(urllib.parse.quote('$resolved', safe=''))")
    url="$MARKETPLACE/api/v1/plugins/download?unique_identifier=$encoded"

    if curl -sSfL "$url" -o "$target.tmp"; then
        mv "$target.tmp" "$target"
        size=$(stat -f%z "$target" 2>/dev/null || stat -c%s "$target")
        printf "  ✓ %-45s  downloaded (%s bytes)\n" "$spec" "$size"
        ok=$((ok + 1))
    else
        rm -f "$target.tmp"
        printf "  ✗ %-45s  download failed\n" "$spec"
        fail=$((fail + 1))
    fi
done

echo
echo "→ done. downloaded=$ok cached=$skip failed=$fail total=$total"

# Emit lockfile. tenant_provisioning_service.py reads this to know which
# unique_identifiers to feed into install_from_marketplace_pkg.
python3 - "$LOCK_FILE" "${LOCK_ENTRIES[@]}" <<'PY'
import json, sys
out_path = sys.argv[1]
pairs = sys.argv[2:]
resolved = {}
for pair in pairs:
    spec, uid = pair.split("=", 1)
    resolved[spec] = uid
with open(out_path, "w") as f:
    json.dump({
        "_comment": "Generated by seed-plugins.sh. Do not edit by hand — rerun seed-plugins.sh after changing default-plugins.json.",
        "resolved": resolved,
    }, f, indent=2, ensure_ascii=False)
PY
echo "→ wrote lockfile: $LOCK_FILE (${#LOCK_ENTRIES[@]} entries)"

if [[ $fail -gt 0 ]]; then
    echo "✗ some downloads failed; rerun later or remove the entries from default-plugins.json" >&2
    exit 1
fi

echo
echo "→ next: restart plugin_daemon so it indexes the new packages"
echo "    docker compose -f $(realpath --relative-to="$PWD" "$SCRIPT_DIR/../docker-compose.yaml" 2>/dev/null || echo dify/docker/docker-compose.yaml) restart plugin_daemon"
